# Generated by Django 3.0 on 2021-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_votocao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_voto',
            name='quantidade_votos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de votos'),
        ),
    ]
