# Generated by Django 3.0 on 2021-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210325_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='horario_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='horario_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
    ]
